### PR TITLE
Moved docker related file in another repo

### PR DESCRIPTION
**Pull request by parruc**
- Moved all dockerfile, entrypoints and nginx confs from backend and frontend repos to new repo
- Commented A LOT of unused imports in backand code
- Commented A LOT of unused dependencies from requirements (maybe something will be needed back):

REMOVED
yarg==0.1.9
joblib==0.17.0
Werkzeug==1.0.1
wrapt==1.12.1
wcwidth==0.2.5
ujson==4.0.1
toolz==0.11.1
thinc==7.4.1
simplegeneric==0.8.1
regex==2020.10.28 
redis==3.5.3
python-memcached==1.59
python-dateutil==2.8.1
pyparsing==2.4.7
PyJWT==1.7.1
pycparser==2.20
ptyprocess==0.6.0
preshed==3.0.2
plac==1.1.3
pipreqs==0.4.10
pickleshare==0.7.5
pexpect==4.8.0
opencv-python==4.4.0.44
olefile==0.46
msgpack==1.0.0
msgpack-numpy==0.4.7.1
MarkupSafe==1.1.1
Jinja2==2.11.2
jedi==0.17.2
itsdangerous==1.1.0
docopt==0.6.2
djangorestframework-jwt==1.11.0
django-bulk-update==2.2.0
django-appconf==1.0.4
dill==0.3.3
decorator==4.4.2
dateutils==0.6.12
config==0.4.2
cython==0.29.21
cytoolz==0.11.0
cymem==2.0.4
cycler==0.10.0
click==7.1.2
chardet==3.0.4
asn1crypto==1.4.0
aniso8601==8.0.0

### CODE REVIEW

**Comment by parruc** [comment]
I broke Docker test pull deleting docker file. Those processes will have to be moved to the docker repo I think

**Comment by derneuere** [comment]
Alright I tested the new images and had a couple of issues. Boot up works fine.
Most errors look like something is wrong with nginx.

 When I rescan my images I get an exception. It is probably just ipdb:
```2021-02-13 04:14:46,974 : directory_watcher.py : scan_photos : 244 : ERROR : An error occured:
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 236, in scan_photos
    walk_directory(user.scan_directory, ps)  # now walk with photo-scannning
  File "/code/api/directory_watcher.py", line 179, in walk_directory
    callback.read_file(fpath)
  File "/code/api/directory_watcher.py", line 206, in read_file
    rescan_image(self.user, path, self.job_id)
  File "/code/api/directory_watcher.py", line 152, in rescan_image
    import ipdb; ipdb.set_trace()
ModuleNotFoundError: No module named 'ipdb'
2021-02-13 04:14:46,982 : directory_watcher.py : scan_photos : 248 : INFO : Added 0 photos
2021-02-13 04:14:55,525 : views.py : get : 1353 : ERROR : [Errno 2] No such file or directory: '[]'
Traceback (most recent call last):
  File "/code/api/views.py", line 1350, in get
    res = [path_to_dict(p) for p in site_config.IMAGE_DIRS.split("\n")]
  File "/code/api/views.py", line 1350, in <listcomp>
    res = [path_to_dict(p) for p in site_config.IMAGE_DIRS.split("\n")]
  File "/code/api/api_util.py", line 46, in path_to_dict
    path_to_dict(os.path.join(path, x), recurse - 1) for x in os.scandir(path)
FileNotFoundError: [Errno 2] No such file or directory: '[]'
```
Adding faces to persons does not work. As soon as you refresh the page, the persons are vanishing. Also I get a GET faces 404 error in the networking tab.

It is not possible to create a new user. I get a POST api/user 500 error.

All the dataviz tabs return error codes:
api/locclust 500
api/albums/user/edit 500
api/locationsunburst 500
api/wordcloud 500
socialgraph 500

It is also not possible to look for locations:
places 404

**Comment by derneuere** [comment]
I think we can use this here to dispatch an event to trigger the librephotos-docker repository to build a new image: https://github.com/peter-evans/repository-dispatch

**Comment by parruc** [comment]
ipdb is now installed only in development mode. To run the development build you can do something like
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache
About 500s seeing the logged errors would help.

**Comment by derneuere** [comment]
The error is pretty easy to recreate. You probably know what it is when you see it :D  I started librephotos in the production mode. Just have a couple of scanned images and click on the wordcloud view. I only see this error from the proxy. There are no errors logged in the backend. The webconsole only has this as error: 
```<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```
Error from the proxy from docker-compose log:
```
proxy_1     | 172.21.0.1 - - [13/Feb/2021:22:14:26 +0000] "GET /api/wordcloud/ HTTP/1.1" 500 145 "http://localhost:3000/wordclouds" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

I would guess it is an issue with the nginx conf and not with the backend.

**Comment by parruc** [comment]
Ops my merge left out a couple of imports: added them back, now looks all dataviz views works again

**Comment by derneuere** [comment]
Nice! The Data Viz Tabs are working again :)

I think there are still a couple of imports missing. You can't create a new album:
```
proxy1 | 172.21.0.1 - - [14/Feb/2021:21:02:20 +0000] "POST /api/albums/user/edit/ HTTP/1.1" 500 145 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x8664; rv:84.0) Gecko/20100101 Firefox/84.0"
```

api/albums/user/edit 500
And you can't open up the places tab:
```
proxy1 | 172.21.0.1 - - [14/Feb/2021:21:02:59 +0000] "GET /api/locclust/ HTTP/1.1" 500 145 "http://localhost:3000/places" "Mozilla/5.0 (X11; Linux x8664; rv:84.0) Gecko/20100101 Firefox/84.0"
```

I also found a new issue: You can't access librephotos from a different computer in the same network. I just get a bad request response:
```
proxy_1 | 192.168.188.27 - - [14/Feb/2021:21:04:30 +0000] "POST /api/auth/token/obtain/ HTTP/1.1" 400 154 "http://192.168.188.83:3000/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"
```

I think I found the reason why my errors aren't logged. Will mark the suspected part.

**Comment by derneuere** [comment]
It seems like a couple imports are missing for the examples when you search something.

```
"proxy_1     | 172.21.0.1 - - [14/Feb/2021:21:20:08 +0000] "GET /api/searchtermexamples/ HTTP/1.1" 500 145 "http://localhost:3000/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

The directory tree for /data is also not appearing anymore if you want to change your path as an admin.

**Comment by parruc** [comment]
Fixed a couple more imports, now looks like search, and other things, are working again.

As for album add I don't think it depends from my changes:

`
backend_1   |   File "/code/api/serializers.py", line 466, in create
backend_1   |     instance.cover_photos.add(obj)
backend_1   | AttributeError: 'QuerySet' object has no attribute 'add'
`

Looks like you were trying to add things to a QuerySet the wrong way, even before my changes. Is it possible?

For the /data situation, I guess with the new frontend this problem wil lgo away, as there you can set your data folder.
What I can do (and just did) is to give it a sensible default "/data" in settings.py that was missing before.

For the network issues I guess something must be changed in the CORS policy and/or INTERNAL_IPS in settings.py
Maybe you can try to reproduce it with the changes I did tonight to have the full logging back also on prd env.

**Comment by derneuere** [comment]
The search is now working better, but still gets an ValueException, which isn't logged... It usually selects random elements to always populate the list with interesting things.
https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/api_util.py#L125-L131

No idea how the UserAlbum worked before :D I removed the cover_photos a while back and just selected the first four images instead. Somehow I never deleted the old functions. Should be safe to remove the conditional add.

https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/models/album_user.py#L27-L29

https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/serializers.py#L462-L467

https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/serializers.py#L482-L483

I don't get any logging in the backend if I try to connect with another computer in the same network. I also don't seem to see the exception when I add a picture to an album.

Will try out the development environment tomorrow and check it with the new frontend.

**Comment by derneuere** [comment]
I think I have figured out, why I can't see the dirtree anymore. I think you forgot to change to the constance setting in this function:
https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/views.py#L1410-L1419

**Comment by parruc** [comment]
> I think I have figured out, why I can't see the dirtree anymore. I think you forgot to change to the constance setting in this function:
> https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/views.py#L1410-L1419

No, I did change it. You are referring to librephoto repo and not to mine (from where the pull request comes) over there. Now it is:

```python
class RootPathTreeView(APIView):
    permission_classes = (IsAdminUser, )

    def get(self, request, format=None):
        try:
            res = [path_to_dict(p) for p in site_config.IMAGE_DIRS.split("\n")]
            return Response(res)
        except Exception as e:
            logger.exception(str(e))
            return Response({'message':str(e)})

```

**Comment by parruc** [comment]
> The search is now working better, but still gets an ValueException, which isn't logged... It usually selects random elements to always populate the list with interesting things.
> https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/api_util.py#L125-L131
> 
> No idea how the UserAlbum worked before :D I removed the cover_photos a while back and just selected the first four images instead. Somehow I never deleted the old functions. Should be safe to remove the conditional add.
> 
> https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/models/album_user.py#L27-L29
> 
> https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/serializers.py#L462-L467
> 
> https://github.com/LibrePhotos/librephotos/blob/f99027a66ea62d304d838fb6e0a68a65fc3e08c9/api/serializers.py#L482-L483
> 
> I don't get any logging in the backend if I try to connect with another computer in the same network. I also don't seem to see the exception when I add a picture to an album.
> 
> Will try out the development environment tomorrow and check it with the new frontend.

from random.sample docs:

If the sample size is larger than the population size, a ValueError is raised.

Maybe you have less than 100 items there? ;-)

If you want to solve the UserAlbum on the pull request we will avoid merge conflict later ;-)

Let me know if yo udiscover something about the "same network" issue. I can't test it having only 1 device ;-) BTW as said before try to play with CORS policy and/or INTERNAL_IPS in settings.py

**Comment by derneuere** [comment]
I opened up a new issue #175 for the search_term_examples.

I will play with the cors settings and change the user repository once I get it to build again :D

**Comment by derneuere** [comment]
Got it running and fixed the issue where you couldn't access LibrePhotos from another computer 👍 
I will look tomorrow into UserAlbums and ipdb. 

After that I think we only have to improve the user experience getting LibrePhotos running :)

**Comment by parruc** [comment]
Great. So it was not about the settings but abut the proxy.
Do you have something specific in mind to improve the user experience? 
Maybe we could also automate (or at least script) the three images building and release process. 
As a reminder just before the merge I will also have to change the repo urls in both BE and FE dockerfile to point to the official repo and not to my fork.

**Comment by derneuere** [comment]
We suddenly had a problem with caching. I changed it so that the cache will be cleared every time something is updated or created. Maybe you know a better way 😅  New dev environment is awesome :+1: 

We currently have users who run LibrePhotos the old way with the dev tag. The old way is preferable to users and us, because they only need the docker-compose.yml file and the .env file and not a complete repository. If they cloned the complete repository, LibrePhotos would crash when we update an entrypoint.sh file or supply a new nginx.conf.

To be backwards compatible we have to:
- Include the entrypoints.sh in the docker images
- Create an image "librephotos-proxy:dev" with the nginx.conf
- Disable SSE4 and AVX Instructions with dlib in the backend

**Comment by parruc** [comment]
nginx.conf have already been moved into the image and only dev env mounts it.
The same can be done for the entrypoints: move them into the image and mount only in dev env. Like this we would keep the prod env as is now and without the need to pull the repo for end users. Does this work for you?

**Comment by parruc** [comment]
As for  SSE4 and AVX Instructions with dlib in the backend I dont know what they are and how to disable them :-D

**Pull request merged**
