### PR TITLE
Add code formatting and linting (black, isort, flake8)

### LINKED ISSUE #87: Enforce an uniform code formatting
Working together on a project is difficult enough without everybody using his own code formatting.  
  
This is why I recommend to switch to a tool called Black which enforces a uniform code style, and which can even be setup as an action, https://github.com/psf/black#github-actions.

### PR DESCRIPTION
**Pull request by reneraab**
Enforcing a common code style enables more collaboration (see #87). This pull request adds a basic pre-commit hook (via [pre-commit](https://github.com/pre-commit/pre-commit)) that calls the black formatter. It should be easy to extend this with additional linting tools or customize the black formatter options defined in `pyproject.toml`. To enable the local git pre-commit hook, `pre-commit` needs to be installed. The hook can be installed via `pre-commit install` (this information should be included in the contributing guidelines).

Feel free to change the settings if you don't think they fit librephotos.

This resolves #87

### CODE REVIEW

**Comment by reneraab** [comment]
I just noticed that the vscode settings contain flake8 and isort and have a different line length setting. If you think that the pre-commit hook and Github Actions integration make sense, I can add those settings as well.

**Comment by derneuere** [comment]
Thank you for your pull request! 

Yes, I think that it would make sense to add flake8 and isort. I don't have any opinion on line length. Just pick a value that makes sense 😄

**Comment by reneraab** [comment]
I added isort, flake8 and pylint to the pre-commit config. There are still some issues though:
- flake8 and pylint should run in the same environment as the rest of the code to ensure the dynamic analysis works
- the same issue applies to the GitHub action
- flake8 and pylint produce *a lot* of errors at the moment and thus block the commit (can still commit via `git commit --no-verify`)

I put this pull request into draft mode until I can fix these issues.

**Comment by reneraab** [comment]
Update: isort and black work out of the box and only need pre-commit to be installed. flake8 works if installed in the current Python environment (this could probably be changed so that it is also handled by pre-commit removing the need to manually install flake8).

pylint and pylint-django (as configured in the .vscode directory) only work from within the Docker container and I have not been able to get them to work within GitHub Actions. The pylint-django plugin actually runs some code which only works well within the Docker environment. pylint without pylint-django works if all required dependencies are present (it adds import errors to its analysis output if the dependencies are missing whereas pylint-django would immediately crash).

So we could either leave out pylint-django and only use pylint (would require all dependencies to be present in the environment where a developer calls `git commit`) or we could try to make the GitHub Action work with pylint-django (probably by putting (part of) the Docker environment into the GitHub action - no clue how that would work exactly). The second option would mean that people could only use the pre-commit hook (and therefore commit changes) from within the Docker development environment. The third and most portable option (i.e. fewest requirements necessary for committing changes/running the pre-commit hook) would be to leave out pylint and pylint-django completely. What do you think, @derneuere?

**Comment by derneuere** [comment]
I think I would stick to the third option for now until linting works within GitHub Actions. We already do some basic linting thanks to SonarCloud and your pull request will already lead to way better code standards than before 😄

**Comment by reneraab** [comment]
I removed pylint from the pre-commit settings. flake8 is not happy with the existing code, but since the pre-commit hook only checks modified files, I think that this is ready to merge (it will only block commits that have issues in one of the modified files). To also make flake8 happy within the GitHub action, one of the next steps should probably involve refactoring the existing code :smile: 

One last thing: It might make sense to take a look at https://pre-commit.ci/ to automate code formatting in commits and pull requests as well as updating the tools on GitHub actions - however, I don't have any experience using it.

<details><summary>flake8 issues</summary>

```
api/views/PhotosGroupedByDate.py:1:1: F401 'datetime' imported but unused
api/views/serializers_serpy.py:2:1: F401 'constance.config as site_config' imported but unused
api/views/serializers_serpy.py:16:9: E722 do not use bare 'except'
api/views/serializers.py:170:9: E722 do not use bare 'except'
api/views/serializers.py:176:9: E722 do not use bare 'except'
api/views/serializers.py:182:9: E722 do not use bare 'except'
api/views/serializers.py:188:9: E722 do not use bare 'except'
api/views/serializers.py:194:9: E722 do not use bare 'except'
api/views/serializers.py:200:9: E722 do not use bare 'except'
api/views/serializers.py:206:9: E722 do not use bare 'except'
api/views/serializers.py:212:9: E722 do not use bare 'except'
api/views/serializers.py:218:9: E722 do not use bare 'except'
api/views/serializers.py:224:9: E722 do not use bare 'except'
api/views/serializers.py:230:9: E722 do not use bare 'except'
api/views/serializers.py:267:9: E722 do not use bare 'except'
api/views/serializers.py:589:9: E722 do not use bare 'except'
api/views/serializers.py:775:9: E722 do not use bare 'except'
api/views/photos.py:2:1: F401 'constance.config as site_config' imported but unused
api/migrations/0003_remove_unused_thumbs.py:1:1: F401 'django.db.models' imported but unused
api/image_similarity.py:5:1: F401 'api.models.User' imported but unused
api/image_similarity.py:38:30: E711 comparison to None should be 'if cond is None:'
api/image_similarity.py:40:30: E711 comparison to None should be 'if cond is None:'
api/im2txt/sample.py:6:1: F401 'numpy as np' imported but unused
api/im2txt/sample.py:12:1: F401 'api.im2txt.build_vocab.Vocabulary' imported but unused
api/im2txt/sample.py:134:5: F821 undefined name 'main'
nextcloud/directory_watcher.py:28:5: E722 do not use bare 'except'
nextcloud/directory_watcher.py:88:9: F841 local variable 'existing_hashes' is assigned to but never used
nextcloud/directory_watcher.py:96:9: F841 local variable 'already_existing_photo' is assigned to but never used
image_similarity/retrieval_index.py:2:1: F401 'json' imported but unused
api/migrations/0011_b_migrate_favorited_to_rating.py:3:1: F401 'constance.config as site_config' imported but unused
api/models/photo.py:16:1: F401 'geopy.geocoders.Nominatim' imported but unused
api/models/photo.py:119:9: E722 do not use bare 'except'
api/models/photo.py:139:13: F841 local variable 'e' is assigned to but never used
api/models/photo.py:173:9: F841 local variable 'e' is assigned to but never used
api/models/photo.py:271:41: E711 comparison to None should be 'if cond is not None:'
api/models/photo.py:282:41: E711 comparison to None should be 'if cond is not None:'
api/directory_watcher.py:154:13: E722 do not use bare 'except'
api/directory_watcher.py:177:9: E722 do not use bare 'except'
api/directory_watcher.py:280:72: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
api/directory_watcher.py:334:70: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
api/models/__init__.py:1:1: F401 'api.models.album_auto.AlbumAuto' imported but unused
api/models/__init__.py:2:1: F401 'api.models.album_date.AlbumDate' imported but unused
api/models/__init__.py:3:1: F401 'api.models.album_place.AlbumPlace' imported but unused
api/models/__init__.py:4:1: F401 'api.models.album_thing.AlbumThing' imported but unused
api/models/__init__.py:5:1: F401 'api.models.album_user.AlbumUser' imported but unused
api/models/__init__.py:6:1: F401 'api.models.face.Face' imported but unused
api/models/__init__.py:7:1: F401 'api.models.long_running_job.LongRunningJob' imported but unused
api/models/__init__.py:8:1: F401 'api.models.person.Person' imported but unused
api/models/__init__.py:9:1: F401 'api.models.photo.Photo' imported but unused
api/models/__init__.py:10:1: F401 'api.models.user.User' imported but unused
api/migrations/0007_migrate_to_json_field.py:18:13: F841 local variable 'e' is assigned to but never used
ownphotos/settings.py:25:8: E713 test for membership should be 'not in'
api/nextcloud.py:3:1: F403 'from api.models import *' used; unable to detect undefined names
api/nextcloud.py:11:23: F405 'os' may be undefined, or defined from star imports: api.models
api/nextcloud.py:14:30: F405 'os' may be undefined, or defined from star imports: api.models
api/nextcloud.py:18:9: E722 do not use bare 'except'
api/face_classify.py:4:1: F401 'pandas as pd' imported but unused
api/face_clustering.py:12:1: E402 module level import not at top of file
api/face_clustering.py:43:32: F821 undefined name 'X'
api/face_clustering.py:93:1: E722 do not use bare 'except'
api/face_clustering.py:130:1: E402 module level import not at top of file
api/models/person.py:34:17: F821 undefined name 'base64'
api/models/person.py:35:24: F821 undefined name 'np'
api/models/person.py:35:47: F821 undefined name 'np'
api/models/person.py:37:25: F821 undefined name 'np'
api/models/person.py:38:35: F821 undefined name 'base64'
api/tests.py:8:1: F403 'from api.models import *' used; unable to detect undefined names
api/tests.py:10:20: F405 'os' may be undefined, or defined from star imports: api.models
api/tests.py:17:9: F405 'User' may be undefined, or defined from star imports: api.models
api/tests.py:30:22: F405 'User' may be undefined, or defined from star imports: api.models
api/tests.py:52:9: F405 'config' may be undefined, or defined from star imports: api.models
api/tests.py:56:9: F405 'User' may be undefined, or defined from star imports: api.models
api/tests.py:134:9: F405 'config' may be undefined, or defined from star imports: api.models
api/tests.py:139:9: F405 'User' may be undefined, or defined from star imports: api.models
api/tests.py:191:35: F405 'os' may be undefined, or defined from star imports: api.models
nextcloud/models.py:1:1: F401 'django.db.models' imported but unused
manage.py:14:13: F401 'django' imported but unused
api/social_graph.py:1:1: F401 'itertools' imported but unused
api/social_graph.py:5:1: F401 'django.db.models.Count' imported but unused
api/social_graph.py:5:1: F401 'django.db.models.Q' imported but unused
api/social_graph.py:7:1: F401 'api.models.Photo' imported but unused
api/social_graph.py:13:9: W191 indentation contains tabs
api/social_graph.py:13:9: E101 indentation contains mixed spaces and tabs
api/social_graph.py:14:9: W191 indentation contains tabs
api/social_graph.py:14:9: E101 indentation contains mixed spaces and tabs
api/social_graph.py:15:9: W191 indentation contains tabs
api/social_graph.py:15:9: E101 indentation contains mixed spaces and tabs
api/social_graph.py:30:13: F841 local variable 'nodata' is assigned to but never used
api/views/views.py:365:9: F841 local variable 'queryset' is assigned to but never used
api/views/views.py:671:9: F841 local variable 'qs' is assigned to but never used
api/views/views.py:1208:29: F821 undefined name 'np'
api/views/views.py:1210:34: F821 undefined name 'np'
api/views/views.py:1215:29: F821 undefined name 'np'
api/views/views.py:1216:24: F821 undefined name 'np'
api/views/views.py:1220:36: F821 undefined name 'np'
api/views/views.py:1232:9: E722 do not use bare 'except'
api/views/views.py:1254:15: F821 undefined name 'build_ego_graph'
api/views/views.py:1295:15: F821 undefined name 'get_photo_country_counts'
api/views/views.py:1311:15: F821 undefined name 'search_similar_image'
api/views/views.py:1352:9: F841 local variable 'e' is assigned to but never used
api/views/views.py:1404:15: F821 undefined name 'is_photos_being_added'
api/views/views.py:1410:15: F821 undefined name 'is_auto_albums_being_processed'
api/views/views.py:1453:1: E402 module level import not at top of file
api/views/views.py:1454:1: E402 module level import not at top of file
api/views/views.py:1569:13: E722 do not use bare 'except'
api/views/views.py:1658:16: E713 test for membership should be 'not in'
```

</details>

**Pull request merged**
