### PR TITLE
Show high-confidence inferred faces in albums

### LINKED ISSUE #354: Minimum confidence for person albums
As a user, I want that high confidence inferred faces are added to the person albums.

This should be configurable and should be by default higher than the minimum confidence for the face recognition (#60). The default should be high enough to get no false positives.

We should add new field "confidence_person" within the user model and add it in the frontend within the settings tab.

### PR DESCRIPTION
**Pull request by jakekapellen**
This partially fixes #354. 90% really shouldn't create many false positives. We could make this configurable very easily by replacing some of the filters on these querysets with a function (using F, I think) that grabs the user's confidence threshold.

I'm opening this pull request to track the approach and signal that I'm willing to work on this. If you want me to add the extra configurability, let me know.

### CODE REVIEW

**Comment by derneuere** [comment]
I think we can solve three open issues with the confidence values:

1. Having clean and useful person albums without bad matches #354 
2. Adding faces automatically to labelled if it is obvious enough 
3. Stop inferring faces with very low confidence to a person  #282 #60

This pull request will solve the first issue well. I think while you are at it, you could easily also add a value for automatically adding faces to a person to solve the second issue. The third issue is mostly solved by the new clustering algorithm, but maybe a cutoff value still makes sense.

While the default makes sense, it would be nice to make a setting for it on the settings page, which is part of the user model.

Let me know if you want to add this in this pull request or if you want to split it in multiple PRs. It would also be great, if you could comment on the issues you want to work on, so that I can assign you to the issues.

**Comment by jakekapellen** [comment]
I'm fine working on all these issues, as they are definitely related. Personally, I think the migration to HDBSCAN fixed the third issue, and I don't think we can easily map a confidence level to any of the parameters in HDBSCAN, and tweaking some of the parameters (like epsilon, probably the closest thing) can have unintended consequences that the user probably isn't well-equipped to understand. I personally think we should close that issue as fixed.

I'd like some clarification on the second issue - do you mean automatically adding inferred faces to Person albums based on their confidence, or automatically marking high-confidence faces as labeled? Based on your description, I think you mean the latter, which has me a little worried if we get this wrong, since labeled faces are never really messed with by the system again, and we'll continue to train faces based on that "labeled" data. This could have unintended consequences after multiple runs. If we do this, I'd want to set the threshold to something like 98% confidence to try to prevent a cascade of mislabeling things.

**Comment by jakekapellen** [comment]
I added the frontend PR: Librephotos/librephotos-frontend#104

**Comment by jakekapellen** [comment]
At this point, the user can specify the confidence level required for an inferred face to show up in a Person album. I tested and all seems to be working.

Give me your feedback on the second issue (what level of confidence makes sense for auto-labeling), and I can make that change as well. That's much simpler (and shouldn't be configurable).

**Comment by derneuere** [comment]
Yeah, I think you are right. I agree, that it should be a very high value and that the cascading effect could be an issue, and would also use something like a 99% confidence. 

I think it makes sense to defer this for now and work on a better labelling experience in the frontend instead.

**Comment by derneuere** [comment]
I think I found another issue when a person has a lot of images. My system has around 70k images and the person has 250 images attached to it. The loading times increased, which is partially because there are more images, but not only. It seems in general to be slower than expected:

Before:
11:48:06.246
200 GET
/api/albums/date/list/
8155ms overall
8112ms on queries
4 queries

With the same number of images:
200 GET
/api/albums/date/list/
54331ms overall
54274ms on queries
4 queries

After:
11:39:49.633
200 GET
/api/albums/date/list/
69569ms overall
69443ms on queries
4 queries

You can look how fast a query was by navigating to api/silk

**Comment by derneuere** [comment]
Alright, I think I found the issue and pushed a change. I was using annotate the wrong way.

**Comment by jakekapellen** [comment]
After merging your changes in, the person albums seem to pull in photos that don't contain the person (all the unknown faces, it seems). I'm testing to see if your change or mine caused the issue (or if I merged it incorrectly).

**Comment by jakekapellen** [comment]
After further testing, merging the dev branch back into my branch introduced the issue. I think some of your changes to try to speed up the People page may have caused the issue. AlbumDateListViewSet, for example, removes a lot of the filtering logic.

**Comment by derneuere** [comment]
Thanks for testing, I reverted the bad change and left a comment for me, what to do the next time I touch it.

**Comment by jakekapellen** [comment]
I retested, and things seem okay now. Let me know if there is anything more you need before merging this PR.

**Comment by derneuere** [comment]
Looks good to me 👍

**Pull request merged**
