### PR TITLE
Push directory scan to worker and add multiprocessing

### PR DESCRIPTION
**Pull request by tomamplius**
Add directory scan to worker queue
Remove some unnecessary update on photo 
 - rewrite _generate_thumbnail
 - reorder albums creation after photo insert
Use multiprocessing with nb process defined in HEAVYWEIGHT_PROCESS variable environment

### CODE REVIEW

**Comment by tomamplius** [comment]
I think add environment variable bellow will be added on  librephotos-docker/backend/entrypoint.sh  for docker 
 ~~~
export DJANGO_SETTINGS_MODULE=ownphotos.settings
~~~

**Comment by rafntor** [comment]
I suspect these changes will undo #131, particularly the memory usage reduction in this commit ; https://github.com/LibrePhotos/librephotos/pull/131/commits/4c41638d3bcbb885453e71fea390a8f6166ab5f6

It could probably be done by adding jobs to the 'pool' as they are found during directory-walking instead of in one big assignment here ;
https://github.com/LibrePhotos/librephotos/blob/76b219d9c74f5d6de21db51aa1ba82f92dcdfab2/api/directory_watcher.py#L206

Otherwise it looks like a great feature 👍 but memory-usage should be considered

**Comment by tomamplius** [comment]
agree, i have create iterable class based on walking directory in my first version.
but map() and startmap() get all value to split them into each process (see https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.map)
I propose that : create db table with temporary data and each process can get unprocess path into the table.
sample table : 
api_directory_scan_pool (  job_id, path , processed ) 
Are you agree?

**Comment by rafntor** [comment]
Hmm I don't quite understand that proposal I'm afraid.
An alternative way could be to build a file-list when walking directory up to a max-size (a few hundred file-paths?) .. and then hand them over to the 'pool' , clear the list, and restart adding to the intermediate list.
But I dont know much about the mechanisms here so I think @derneuere must advice what is best

**Comment by tomamplius** [comment]
Sorry for my English!!
Create fork is a big cost because of the memory required, restart starmap is not a good idea i think. 
My proposition is create list of image path to process in database and processes get image path to process from database. There stop when no path to process. In this way there is no memory use to the path list, whatever the number of files

**Comment by tomamplius** [comment]
On my last test with 16840 photos with 6 heavy processes 1Go on Ram only 

image

**Comment by derneuere** [comment]
Thanks for your pull request!

Sorry for my late reply, didn't have a lot of time in the last couple of weeks and had to look over your older pull requests! :D

Do we know how starmap behaves when it is used in a big library? Like a libaray of one TB of photos?

Also starmap seems to have a parameter "chunk size", which should improve memory usage, because it allows us to iterate in chunks. I think the chunk size should be the number of the number of heavyweight processes, or?

I am not a fan of a temporary table because I want to keep the data structure lean.

**Comment by tomamplius** [comment]
I have commit my old version with iterator. 
But this version need 2 folders scan.
On all my test with chunk size all files are scan before launch processes (add log in walk dir) . whatever the value of chunk all a files a send into the log.

**Comment by tomamplius** [comment]
@rafntor @derneuere 
I hope that new commit will be ok for you.
I become a multiprocesses expert :-)

**Comment by tomamplius** [comment]
after some thought i don't know if it's good because a directory is only handled by one process

**Comment by tomamplius** [comment]
I will rewrite with "push photo to queue"

**Comment by tomamplius** [comment]
Thank for your comment. This version work good, without list of path

**Comment by tomamplius** [comment]
After check List with 180000 time the string "/var/lib/librephotos/data/photos/2020/02-février/Escapade à Cabourg 17 au 20 février/20200217_165525.jpg" take 19Mo in a file.

~~~

**Comment by tomamplius** [comment]
I'm come back to the first version
After check List with 180 000 time the string "/var/lib/librephotos/data/photos/2020/02-février/Escapade à Cabourg 17 au 20 février/20200217_165525.jpg" take 19Mo in a file (in UTF8).
~~~
>>> import sys
>>> a=[]
>>> for tmp in range(180000):
...  a.append("/var/lib/librephotos/data/photos/2020/02-février/Escapade à Cabourg 17 au 20 février/20200217_165525.jpg")
... 
>>> sys.getsizeof(a)
1443576
~~~
This means that the list take 1.443576 MB... in memory (1443576 bytes)
Lot of time lost to win nothing
Fork take between 1 and 2 Go the cost is here

**Comment by derneuere** [comment]
Hmm, maybe the problem wasn't the list but something else.
I merged dev into your branch. Could you check if the multiprocessing still works with wand/imagemagick or if I broke it?

**Comment by tomamplius** [comment]
Except issue #211, all working good after the both "Merge branch 'dev' into multiproc"
By default, there is one process

image

**Comment by rafntor** [comment]
Perhaps the list-problem was something else yes ... but I am very uncertain - without the fix my setup was unable to do any scanning and the time spent counting files is negligible compared to time spent analyzing photos.

And I am not sure the quick test above is conclusive ; 
``` python
>>>
>>> import sys
>>> a=[]
>>> for tmp in range(180000):
...   a.append("X")
...
>>> sys.getsizeof(a)
1443576
>>>
```

**Comment by tomamplius** [comment]
There is other way to check
image

**Comment by tomamplius** [comment]
But you are right test is not conclusive
~~~
for tmp in range(180000):
...   a.append("/var/lib/librephotos/data/photos/2020/02-février/Escapade à Cabourg 17 au 20 février/" + str(a) + ".jpg")

**Comment by tomamplius** [comment]
Maybe you are right about the conclusive test.
Bellow test with not the same string (using the tmp value in the string)
180 000 string take 8MB in this case
image

**Comment by derneuere** [comment]
@rafntor Could you test this PR with your large library to check if it leads to a memory leak?

**Comment by rafntor** [comment]
Sure, but I dont have environment to build it ; could you provide a test-image ?

**Comment by rafntor** [comment]
It seems to run just fine 👍 
But, surprisingly I see no performance impact, scanning-time and memory-usage are very similar - a 15 minute test-run imports ~110 pictures on my system both with and without these changes.
Running docker desktop on windows in wsl2 mode, on AMD Ryzen 7 1700 (8 cores)

**Comment by tomamplius** [comment]
Yes by defaut the number of process is 1
Set HEAVYWEIGHT_PROCESS=3
I have import 16000 photos in 32h. With current version 80h. But memory use is 3 times more use

**Pull request merged**
