### PR TITLE
Add owncloud photo on scan command

### PR DESCRIPTION
**Pull request by tomamplius**

### CODE REVIEW

**Comment by derneuere** [comment]
This should be a separate command, because the ownphotos scan also downloads images to librephotos. I don't think most people are aware of that.

**Comment by tomamplius** [comment]
Sorry, i don't understand why. 
nextcloud photos are download in settings.DATA_ROOT +'/nextcloud_media'
normal scan will scan in user.scan_directory

**Comment by tomamplius** [comment]
Wait about https://github.com/LibrePhotos/librephotos/issues/247 to merge or remove this PR

**Comment by derneuere** [comment]
Sorry for the late reply! 

I think this should be added as an extra argument, like we did with the full scan command.

**Comment by npsqm** [comment]
I would be happy to implement it as an extra argument. It is the last missing puzzle piece to my picture workflow so I would really like to see that happen soon. Since #247 seems to be a bigger issue and this one here is so small and could be easily refactored at any time, I think it would be really nice to move forward here and not to wait.

@tomamplius, since you already started this, would you like to finish it or would it be alright for you if I would do that?

**Comment by derneuere** [comment]
@npsqm I think we waited long enough. You can implement it 👍

**Comment by npsqm** [comment]
Awesome, thanks @derneuere. I will create a new PR in the next days :)

**Comment by derneuere** [comment]
Superseded by #402

**Pull request closed without merging**
