### PR TITLE
Configurable date time extractor

### PR DESCRIPTION
**Pull request by pivis**
This PR introduces a configurable extractor for date/time (related to https://github.com/LibrePhotos/librephotos/issues/300). The parameters for each rule are defined by a plain JSON-compatible dictionary. This version doesn't include any per-user customization, but the goal is to eventually add configuration as per-user setting and provide UI for users to specify the logic.

The default logic is defined by `DEFAULT_RULES_PARAMS`:
1. Try to use photo exif tag with local date time
2. Try to use video creation datetime in UTC and translate to local timezone using GPS coordinates
3. Try to extract datetime from filename
4. Try to use video creation datetime in UTC (without fixing local timezone)

Copying the comment from the code about currently supported rules:

```
    The goal is to help extract local time, but for historical reason it is expected the returned
    datetime will have timezone to be set to pytz.utc (so local time + timezone equal to UTC)..
    Some sources of data might give us very rich information, e.g. timestamp + timezone,
    but others only allow to get local time (without knowing real timestamp).
    The logic for extracting local time is described as a list of rules that should be applied
    one after another until one rule is able to extract date time (or until all rules are tried
    without success).

    Currently supported rule types:
      - "exif" - local time is taken using exif tag params["exif_tag"] as obtained with exiftool
      - "path" - time is taken from the filename using a regular expression matching
        - if params["path_part"] is set to "full_path" then full path (as seen by backend container)
          is used for regexp matching instead of just fileanme.
        - if params["custom_regexp"] is specified - that regexp is used instead of default one
          (it is still expecting 6 groups to be matched: year, month, day, hour, minute, second).
      - "fs" - time is taken from file property. Since these are unix timestamps without timezones
        they are always translated to local time using UTC.
        - params["file_property"] must be specified and equal to one of the following:
          - "mtime" - for file modifided time
          - "ctime" - for file created time

    If a rule can't fetch the time (e.g. the exif tag value is not present or path doesn't match
    a regexp) then that rule is considered to be not applicable.

    In some cases it is known that the local time the rule would obtain is not in the desired
    timezone. E.g. video datetime tag QuickTime:CreateDate is by standard written in UTC rather
    than local time. For such cases each rule can optionally have setting "transform_tz" set to "1"
    - in that case this rule should also specify "source_tz" and "report_tz" settings where
    "source_tz" is describing the timezone that the rule is getting and "report_tz" is describing
    the timezone of the location where the photo/video was taken. Both "source_tz" and "report_tz"
    should be one of the follwing:
      - "utc" - UTC timezone
      - "gps_timezonefinder" - the timezone of the GPS location associated with the photo/video
      - "name:<timezone_name>" - the timezone with the name <timezone_name>
    If either "source_tz" or "report_tz" could not be obtained the rule is considered to be not applicable.

    Examples of the rules:
      - Take local time from exif tag "EXIF:DateTimeOriginal" if it is available:

            {
                "rule_type": "exif",
                "exif_tag": "EXIF:DateTimeOriginal",
            }

      - Take UTC time using tag "QuickTime:CreateDate" and convert it from UTC
        to timezone associated with the GPS coordinates (only applies if both
        tag value and GPS coordinates are available):

            {
                "rule_type": "exif",
                "exif_tag": "QuickTime:CreateDate",
                "transform_tz": 1,
                "source_tz": "utc",
                "report_tz": "gps_timezonefinder",
            }

      - Look at the filename and try to extract time from it - treat it as local time
        (it is known that some devices are not using local time here - e.g. some phones
        might use UTC time for video filenames):

            {
                "rule_type": "path",
            }

      - Take UTC time time using tag "QuickTime:CreateDate" and convert it from UTC
        to a fixed timezone "Europe/Moscow" to get local time:

            {
                "rule_type": "exif",
                "exif_tag": "QuickTime:CreateDate",
                "transform_tz": 1,
                "source_tz": "utc",
                "report_tz": "name:Europe/Moscow",
            }

      - Take modified time of the file and get local time using timezone associated
        with the GPS location:

            {
                "rule_type": "filesystem",
                "file_property": "mtime",
                "transform_tz": 1,
                "source_tz": "utc",
                "report_tz": "gps_timezonefinder",
            }
```

### CODE REVIEW

**Comment by pivis** [comment]
Configuration per-user could be stored as a json field, but for the UI we will have to decide how customizable we want to go. E.g. we can"
  1. Pre-configure some rules and let users add rules from that list and re-order them as them like.
  2. Provide more customizable UI to add new rules (allowing e.g. specifying exiftool tag names as a string) to the reorderable list.

**Comment by pivis** [comment]
I also think about some extra possible things I can add here (but they would definitely require additional frontend support) - most importantly conditions for the rules:

E.g. each rule could additionally have fields like:
    1. "if_path_matches_pattern": "<regexp>" - if this property is present then image/video path is first compared to the given regexp and only applied if there is a match. Reason: allow some rules to be only specific to a folder or a set of folders. Similarly we could have "if_filename_matches_pattern".
    2. "if_exif_tag_matches" - this would provide 2 things: exif tag name and pattern. This could e.g. allow to create rules that are only applicable to a specific Camera etc. (though e.g. same phone might set the tag for image, but not able to set it for videos, still - this might be useful).

But again, the most important part here would be the frontend support.

**Comment by pivis** [comment]
I went ahead and added `condition_path`, `condition_filename`, `condition_exif`  conditions to be supported by the rules to allow creation of rules that could be only applied to e.g. specific folder(s) based on the full path or based on filename patterns, etc. E.g. one could say that they want to create higher-priority rule based on filename but only if filename contains a specific prefix (or does not contain it using a negative look-arounds: `^(?!PXL_).*$` for filename not starting with `PXL_`). Also one could create rule to only apply to files with `EXIF:Model` containing given pattern, etc.

**Comment by derneuere** [comment]
This looks awesome! Thank you for working on this 👍 

My view on the priority of the features is the following:

- We should have a good default, that works for most people
- The next important thing is, that you can reorder and delete/add preconfigured rules
- The last thing would be custom rules. I like it as a feature for power users, but most people are not power users.

Parsing file names: 

We should clean up the timestamps by giving a range of possible times. What often happened in the past is that we would parse a timestamp, that is far in the future / past, which is obviously not wanted. 

I think preconfigured rules for WhatsApp Images and other common apps would be great, as they follow clear schemas.

Parsing Google Photos:

Google Photos gives you a jpg.json file when you download all your images via takeout, where the metadata is saved. That's an edge case, and possibly it's just a separate feature all together.

This could be used to do that: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper

Not sure how Apple Photos and Amazon Photos behaves on export, but that is something that could be looked into.

Parsing date of folders:

I think some people do not know about EXIF timestamps and sort their images by putting it into folders based on month and year. This could be done with the "path" rule, I think.

For the frontend:

Adding it to the user as a json field is a good idea.
A name attribute for the rules would be great to display it better to the user.

**Comment by derneuere** [comment]
I created a basic mockup of the UI:
image

Anything you want to add to it?

**Comment by pivis** [comment]
Thank you for such a quick response, @derneuere . I absolutely agree regarding the priorities (good defaults, simple configuration, advanced configuration).

> We should clean up the timestamps by giving a range of possible times. What often happened in the past is that we would parse a timestamp, that is far in the future / past, which is obviously not wanted.

Regarding parsing the filenames I currently use YYYY expectation for the year (and first 2 digits should be either 19, 20 or 21 (I'm an optimist)). It also  still might match weird things like 20210230 (February 30), but it does only match day between 1 and 31, so hopefully such cases should be not very common (good thing would be to add logic to process incorrect dates). If you think this is not enough we definitely can introduce min/max date (on any level - per rule, configurable per user, or just hardcode as a default though I'd feel a bit bad imposing non-changeable defaults here). To be honest I'd say that min date might be more applicable not even to filenames, but more for the filesystem times - e.g. 1970 year from timestamp is much more likely to be just 0 timestamp than genuine file from 1970 :).

> I think preconfigured rules for WhatsApp Images and other common apps would be great, as they follow clear schemas.

Could you please clarify this part? I'd love to learn more about these cases.

> Parsing Google Photos ...

I was under impression (and sort of still is) that current Librephotos way of extracting data is extracting json sidecar files' data (if you ask exiftool module to give you all tags you will see `JSON:...` and also I think `COMPOSITE:...` is something like a merged version (not sure about that, just my guess). One thing I'd add here is that python `exiftool` module tag naming seems to be different from e.g. using CLI `exiftool -a <filename>` - say, `EXIF:Model` is alled `Camera Model Name` when you use `exiftool -a ...` - if we allow people to create their own rules it would be nice to somehow let people see e.g. all exiftool tags of a given image.

> I think some people do not know about EXIF timestamps and sort their images by putting it into folders based on month and year. This could be done with the "path" rule, I think.

I really like this idea, but it is only very partially supported with the current rules (requires dates to be numerical and all 6 pieces to be present in the order of year/month/day/hour/minute/second for regexp capture groups). Would love to implement something that would support stuff like only giving date but not time with path names (or maybe even just year or year+month). We can discuss this separately, but I don't think any of that would likely to fall under "advanced configuration" by power users.

> A name attribute for the rules would be great to display it better to the user.

That sounds like a good thing - and in the backend we can add some logging that is referencing rules' names e.g. for match to clarify how we extracted time for a given file.

## Frontend

I like the mockup. I'd probably prefer some simpler things to be shown e.g. for default rules that are auto-added (with maybe some explanation/hints under question mark on hover): something like
`Photo local time`
`Video creation time (+fix timezone using GPS)`
`From filename`
`Video creation time in UTC`
It is still ok to show more info I think, but it would be nice to have a simple explanation nearby.

I think we should provide at least one of 2 things:

  1. A way to create new rules (even if it is just selecting from a list of predefined rules).
  2. A way to disable/enable existing rules (might be a nice feature for power users too) - if this is enabled we theoretically could just add all simple rules to the list with only a subset enabled.

**Comment by derneuere** [comment]
I think I will test it and then be more specific if something is off. It will probably be an incremental thing.

Here is an exemplary issue regarding WhatsApp Images: https://github.com/LibrePhotos/librephotos/issues/416 

Very cool that exiftool already supports that. Didn't know that! Yes, adding all exif tags would be a good thing.

**Comment by derneuere** [comment]
Looks good to me!

**Pull request merged**
