### PR TITLE
changes for new download api

### PR DESCRIPTION
**Pull request by AnkurPrabhu**
Issue Link #375  @derneuere 
what has been done :
- have created a job type in `long_running_job` for download 
- created two method one for making the zip file  i.e `zip_photos_task` and second which call the zip function i.e `create_download_job`
- created a get api for the same view class which checks the status of the running job 

Pending:
- checking file system storage before starting the zipping process
- test file 

doubts :
- for checking storage size i was thinking about checking the total size of all the photos and depending upon the size will have an estimate ......not sure how to go about it 
- also i kind of figured out why the existing method was not working, the issue was not because of the download function it was while sending the file as the file size becomes too large it takes a lot of time to send the zip file as one response thats the reason it takes time is what i feel because i used my method for only 2 files and it took 2 secs for it so assuming even if we download 40 images it might take a lot of time to send it as a whole so i think we need to do something like pagination for sending data which might solve the issue let me know if i am thinking in the right direction or not as others can test this and we can discuss this  .
- is it okay if i create the test files in a separate pr ?
- also i have commented out some code in `zip_photos_task` for importing torch and making a thread was not sure if i actually needed it

### CODE REVIEW

**Comment by derneuere** [comment]
- You can use shutil for checking how much space is available.  https://github.com/LibrePhotos/librephotos/blob/602d622fef52d3bc2bc3bfdc97496e6abe88dac6/api/api_util.py#L326 An estimate counting all the file sizes of the media file should work fine! 
- Hmm, that could be an issue. When we view large media files, we do that by rerouting it to nginx. This could work for the zips too! If you need more guidance than a pointer, you can always ask :) https://github.com/LibrePhotos/librephotos/blob/602d622fef52d3bc2bc3bfdc97496e6abe88dac6/api/views/views.py#L337 https://github.com/LibrePhotos/librephotos-docker/blob/main/proxy/nginx.conf
- Torch is only needed when doing AI stuff, which we are not doing here. You can remove that.
- You can create the test in a separate PR and link it, but I would not recommend that as testing than becomes kind of hard, because you have to switch between branches.

Only one small nitpick I found when browsing through your code: It would be nice to only have one migration file for the new job type.

**Comment by AnkurPrabhu** [comment]
> * Hmm, that could be an issue. When we view large media files, we do that by rerouting it to nginx. This could work for the zips too! If you need more guidance than a pointer, you can always ask :) https://github.com/LibrePhotos/librephotos/blob/602d622fef52d3bc2bc3bfdc97496e6abe88dac6/api/views/views.py#L337
>    https://github.com/LibrePhotos/librephotos-docker/blob/main/proxy/nginx.conf

from your comment this is what i understood : 
- i have to create a new condition in the file `_generate_response` like 
   if "zip" in filename:
                response["Content-Type"] = "zip"
                response["X-Accel-Redirect"] = self._get_protected_media_url(
                    path, fname + ".ZIP"
                )
is that it please let me know if i am missing something

**Comment by derneuere** [comment]
I would do a path check first!

```if "all_zip_folder" in path:```

But you can also always just check it with the endpoint /api/media/all_zip_folder/<filename>.zip
Not sure if I like the name all_zip_folder. I think just zip would be enough.

**Comment by sickelap** [comment]
@AnkurPrabhu could you please merge migrations into one? No need to have two when updating the same table.

**Comment by derneuere** [comment]
@sickelap He already did that and opened up a new pull request! I think this one here was only open, because of his question :)

**Comment by AnkurPrabhu** [comment]
> I would do a path check first!
> 
> `if "all_zip_folder" in path:`
> 
> But you can also always just check it with the endpoint /api/media/all_zip_folder/.zip Not sure if I like the name all_zip_folder. I think just zip would be enough.

cool will rename it also do i have to make any changes in the nginx file also how is rerouting to nginx helping does it automatically streams data in chunks for something ? or its just pointing a location as we run our app locally 



> @AnkurPrabhu could you please merge migrations into one? No need to have two when updating the same table.

i have made a new pr only lets close this one and continue our conversation there #1057

**Pull request closed without merging**
