### PR TITLE
Add a feature that allows patterns in filenames/directories to be ign…

### PR DESCRIPTION
**Pull request by maestro-pkt**
…ored

This should partially address #64.

### CODE REVIEW

**Comment by maestro-pkt** [comment]
Can I get an update on when this might get merged?  Thanks!

**Comment by derneuere** [comment]
I haven't gotten around to test it yet. 
I am pretty sure that it will not work with older .env and docker-compose files, because it will not have a skip pattern env variable. Could you add a check if os.getenv('SKIP_PATTERNS') is not available then return false?

**Comment by maestro-pkt** [comment]
Thank you for pointing that out.  I’ll add that check.

**Comment by derneuere** [comment]
Tested it and it still works on my machine. Thanks for your pull request :+1:

**Comment by kicker334** [comment]
I must be a doof because I can't figure out why I'm getting an error whenever I fill in the skipPhotos environment variable. If I leave it blank, it will scan directories. If I put one word in, it falls with the message below. I used the instructions on the readme to build the Docker containers. All other environment variables work... Just not skip. Any help would be appreciated. Thank you! 

```
2021-02-16 04:50:44,429 : directory_watcher.py : scan_photos : 242 : ERROR : An error occured:
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 230, in scan_photos
    walk_directory(user.scan_directory, fc)
  File "/code/api/directory_watcher.py", line 173, in walk_directory
    if not is_hidden(fpath) and not should_skip(fpath):
  File "/code/api/directory_watcher.py", line 46, in should_skip
    skip_list = map(str.strip, skipList)
NameError: name 'skipList' is not defined
2021-02-16 04:50:44,430 : directory_watcher.py : scan_photos : 246 : INFO : Added 0 photos
```

**Comment by kicker334** [comment]
It looks like a user submitted a commit to fix this. #173

**Pull request merged**
