### PR TITLE
#310: Use rating for favorited

### PR DESCRIPTION
**Pull request by jmalm**
Add rating to and remove favorited from the Photo model. Migrate data: `favorited==true` => `rating=4`.

Show photos with a rating greater than a user-set minimum rating (default 4) as favorited.

When a user marks a photo as favorite, set rating to that same favorite minimum rating.

Admin can set the default favorite minimum rating for new users.

This PR should be merged together with the one in frontend (https://github.com/LibrePhotos/librephotos-frontend/pull/21).

### CODE REVIEW

**Comment by jmalm** [comment]
I implemented this with a site setting first, but then added the user setting, using the site setting as a default. The site setting is perhaps a bit unnecessary now...

**Comment by derneuere** [comment]
Thank you again for opening up the pull request! The code looks in general looks good to me, but I found a couple of issues.

As you said, the site setting seems redundant. I think it should be removed.

I found a bug. If you add a photo to favorites within the "With Timestamps" view and then switch to the favorites view, then the site crashes. If you refresh the favorites view everything works again. It looks like an issue with a redux store. The items are manipulated in way that makes react-pig crash.

```
TypeError: g.items is undefined
computeLayoutGroups/<
src/app/node_modules/react-pig/dist/index.es.js:5898

  5895 | // the working rowAspectRatio.
  5896 | 
  5897 | var tempImgData = [];
> 5898 | g.items.forEach(function (image, index) {
       | ^  5899 |   if (index === 0) {
  5900 |     groupTranslateY = translateY;
  5901 |   } 
```

**Comment by jmalm** [comment]
Aww, great that you found this. I will reproduce and fix.

I will also remove the added site setting.

**Comment by jmalm** [comment]
I can reproduce the bug with and without the changes in this PR (and https://github.com/LibrePhotos/librephotos-frontend/pull/21, having migrated the database back).

So, definitely a bug, but not caused by these changes.

I think that it should also be solved naturally by the changes I'm currently doing to use one single photos list in the frontend.

**Comment by jmalm** [comment]
I found the issue, I think. When adding a photo as favorite, it's just added to `store.photos.favoritePhotos` directly, but the `FavoritePhotos` view expects `store.photos.favoritePhotos` to be a date-grouped list. This will definitely change in my current refactoring.

Relevant code from photoReducers.js:
```js
      if (valFavorite) {
        updatedPhotos.forEach(photo => {
          newFavoritePhotos.push(photo);
        });
      } else {
        newFavoritePhotos = newFavoritePhotos.filter(photo => {
          if (updatedPhotosImageHashes.includes(photo.image_hash)) {
            return false;
          } else {
            return true;
          }
        });
      }
```

**Comment by derneuere** [comment]
I could also reproduce the bug on the demo server, which obviously does not have the changes in this PR. I think after the removal of the site setting, this can be merged 👍 

I will file an issue to document the bug 😄

**Comment by jmalm** [comment]
Default favorite min rating removed from site settings. I did make it possible to supply the default as an environment variable though (DEFAULT_FAVORITE_MIN_RATING). If you think it would be good, I'll create a PR in librephotos-docker with this as an added optional setting.

**Comment by derneuere** [comment]
Yes, this makes sense :+1: 

Looks good to me!

**Pull request merged**
