### PR TITLE
Add object detection

### PR DESCRIPTION
**Pull request by derneuere**
This commit adds object detection to LibrePhotos. It has currently a memory leak issue, so don't merge it yet!

### CODE REVIEW

**Comment by derneuere** [comment]
Memory issue is now better, but the RAM Usage is just too high (around 4GBs)
Also I am running into a timeout, because the process is taking too long. I will look into rq worker again and will try to make them work again I think.

**Comment by derneuere** [comment]
I changed it to a new version of darknet and only instatiated it once. It still does not release the RAM after a run.

**Comment by driehuis** [comment]
I think memory usage will always be an issue with darknet. Would it be an idea to (a) make object detection a configurable option, and (b) create a simple network protocol and run darknet in its own docker container?

One of the side effects of splitting off object detection would be that it allows to farm out that task to an nvidia jetson or a GPU in the cloud. This would also open up object detection for experimentation without fear of breaking librephotos proper, if the network protocol allows for breaking gracefully.

**Comment by thelittlefireman** [comment]
Maybe we could put this part in a dedicated docker ? A New intressting project pop up called jina. A text to image search accessible through rest api (https://github.com/jina-ai/examples/blob/master/object-search)

**Comment by dcflachs** [comment]
Just dropping in to suggest basing this around the TensorFlow Serving REST API. Tensorflow serving is a convenient way to stand up  various model types for remote inference. Additionally both intel and nvidia have model servers optimized for their accelerator architectures which use variants of the TensorFlow Serving REST API. All are available in docker. I would love to see librephotos move all of its inference based workflows to using REST based model server(s). It would make allocating the proper hardware for hosting more flexable.

**Pull request closed without merging**
