### PR TITLE
backend apis for filtering only photos and only videos 

### PR DESCRIPTION
**Pull request by AnkurPrabhu**
issue: Video library filter [#750](https://github.com/LibrePhotos/librephotos/issues/750)
what has been done :
 have created 2 backend apis for filter only videos and only photos
  1)  ` ViewOnlyVideoListViewSet`
  2)  `ViewOnlyPhotoListViewSet`

### CODE REVIEW

**Comment by derneuere** [comment]
Sorry, I probably should have specified, how images work in LibrePhotos :sweat_smile: 
https://docs.librephotos.com/docs/development/contribution/backend/photo-list

The issue is, that the simple way does not scale that well. We divide all images into time buckets called album_date, which we then load instead. To accurately determine the timeline view however, we need to know all dates and how many images there are for each day, to calculate the horizontal length. 

The endpoints you have to modify are:

https://github.com/LibrePhotos/librephotos/blob/c7a015614f923ba8e09678b1c8058041e9fc643d/api/views/albums.py#L307

https://github.com/LibrePhotos/librephotos/blob/c7a015614f923ba8e09678b1c8058041e9fc643d/api/views/albums.py#L447

These already have a video parameter! This means you only have to add a photo only parameter :)

**Comment by AnkurPrabhu** [comment]
@derneuere  hey i have made the changes as per what i understood please let me know if any changes also i have made the front-end changes and everything seems to be fine its just that the commit hooks are throwing errors on some already existing methods and some on my components too so how should i go about it ?

**Comment by derneuere** [comment]
@AnkurPrabhu As long as your committed code passes the commit hooks, you can open a pull request. The old methods and components, that you did not change, can be ignored, but it would also be nice if you could fix a couple of issues :)

**Comment by sickelap** [comment]
Would be nice to have at least some integration tests covering new functionality

**Comment by AnkurPrabhu** [comment]
@sickelap  while writing test why does the call to `/api/albums/date/list/?photo=true` return empty am i doing something wrong ?
Screenshot 2023-10-22 at 8 19 36 PM

**Comment by derneuere** [comment]
@AnkurPrabhu You need to be authenticated, otherwise only public photos will be shown. You can either set the photo as public or add a user to the client, when asking for the photos :)

**Comment by AnkurPrabhu** [comment]
> @AnkurPrabhu You need to be authenticated, otherwise only public photos will be shown. You can either set the photo as public or add a user to the client, when asking for the photos :)

i have used `force_authenticate` in the setup it still doest work 
Screenshot 2023-10-22 at 9 09 15 PM

**Comment by sickelap** [comment]
better would be to add owner to a photo. we could help if you push your changes into branch PR :)

**Comment by AnkurPrabhu** [comment]
> better would be to add owner to a photo. we could help if you push your changes into branch PR :)

what is a branch pr ...i am not allowed to make a remote branch in this repository as i do not have create access so i forked it and then made a pr

**Comment by sickelap** [comment]
well, I din't see any changes in your forked branch. if you could make them available we would have what to talk about :)

**Comment by AnkurPrabhu** [comment]
@sickelap i have added a test file ..i went through the db and found out that u have to create an album in order to get the results so pls review the test file for photos will do the same for only videos api

**Comment by AnkurPrabhu** [comment]
> well, I din't see any changes in your forked branch. if you could make them available we would have what to talk about :)

have pushed the changes here pls have a look  @sickelap @derneuere

**Comment by AnkurPrabhu** [comment]
hey @sickelap any update on this one ?

**Pull request merged**
